services:
  db:
    image: postgres:latest
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - .env.db.example
  redis:
    image: redis:latest
  server:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    env_file:
      - .env.server.example
